/*체험학습을 2개 이상 신청한 아이의 정보와 부모의 정보 모두 조회*/
SELECT FIELD_TRIP_ID, COUNT(CHILD_ID) FROM TBL_APPLY
GROUP BY FIELD_TRIP_ID
HAVING COUNT(CHILD_ID) >= 2;

SELECT * FROM TBL_PARENT P
INNER JOIN
(
   SELECT * FROM TBL_CHILD
   WHERE ID IN
   (
      SELECT CHILD_ID FROM TBL_APPLY
      GROUP BY CHILD_ID
      HAVING COUNT(FIELD_TRIP_ID) >= 2
   )
) C
ON P.ID = C.PARENT_ID;

/*참가자(지원자) 수가 가장 적은 체험학습의 제목과 내용 조회*/
SELECT * FROM TBL_FIELD_TRIP;
SELECT * FROM TBL_APPLY;

SELECT FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT FROM TBL_FIELD_TRIP
WHERE ID =
(
   SELECT FIELD_TRIP_ID FROM TBL_APPLY
   GROUP BY FIELD_TRIP_ID
   HAVING COUNT(CHILD_ID) =
   (
      SELECT MIN(CHILD_COUNT) FROM
      (
         SELECT FIELD_TRIP_ID, COUNT(CHILD_ID) CHILD_COUNT FROM TBL_APPLY
         GROUP BY FIELD_TRIP_ID
      )
   )
);

/*평균 참가자(지원자) 수보다 적은 체험학습의 제목과 내용 조회 */
SELECT FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT FROM TBL_FIELD_TRIP
WHERE ID IN
(
   SELECT FIELD_TRIP_ID FROM TBL_APPLY
   GROUP BY FIELD_TRIP_ID
   HAVING COUNT(CHILD_ID) <
   (
      SELECT AVG(CHILD_COUNT) FROM 
      (
         SELECT COUNT(CHILD_ID) CHILD_COUNT FROM TBL_APPLY
         GROUP BY FIELD_TRIP_ID
      )
   )
);

DROP SEQUENCE SEQ_POST;
CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(1000) NOT NULL
);

CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(1000) NOT NULL,
	POST_CONTENT VARCHAR2(1000) NOT NULL,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '한동석');
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '홍길동');
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '이순신');
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '장보고');

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 3);
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 4);
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 4);
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 3);
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 3);
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 3);

SELECT M.ID, M.MEMBER_NAME, COUNT(P.ID) FROM TBL_MEMBER M
LEFT OUTER JOIN TBL_POST P
ON M.ID = P.MEMBER_ID
GROUP BY M.ID, M.MEMBER_NAME;









