/*체험학습*/
CREATE SEQUENCE SEQ_PARENT;


CREATE TABLE TBL_PARENT(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_NAME VARCHAR2(1000) NOT NULL,
	PARENT_AGE NUMBER,
	PARENT_ADDRESS VARCHAR2(1000) NOT NULL,
	PARENT_PHONE VARCHAR2(1000) NOT NULL UNIQUE,
	PARENT_GENDER VARCHAR2(1000) NOT NULL
);

CREATE SEQUENCE SEQ_CHILD;


CREATE TABLE TBL_CHILD(
	ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
	CHILD_NAME VARCHAR2(1000) NOT NULL,
	CHILD_AGE NUMBER,
	CHILD_GENDER VARCHAR2(1000) NOT NULL,
	PARENT_ID NUMBER,
	CONSTRAINT FK_CHILD_PARENT FOREIGN KEY(PARENT_ID)
	REFERENCES TBL_PARENT(ID)
);

CREATE SEQUENCE SEQ_FIELD_TRIP;

CREATE TABLE TBL_FIELD_TRIP(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
	FIELD_TRIP_TITLE VARCHAR2(1000),
	FIELD_TRIP_CONTENT VARCHAR2(1000),
	FIELD_TRIP_NUMBER NUMBER
);

CREATE TABLE TBL_FIELD_TRIP_FILE(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP_FILE PRIMARY KEY,
	FILE_ORIGINAL_NAME VARCHAR2(1000) NOT NULL,
	FILE_SYSTEM_NAME VARCHAR2(1000) NOT NULL,
	FILE_POSITION VARCHAR2(100),
	FIELD_TRIP_ID NUMBER,
	CONSTRAINT FK_FIELD_TRIP_FILE_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
	REFERENCES TBL_FIELD_TRIP(ID)
);

CREATE SEQUENCE SEQ_APPLY;

CREATE TABLE TBL_APPLY(
	ID NUMBER CONSTRAINT PK_APPLY PRIMARY KEY,
	CHILD_ID NUMBER,
	FIELD_TRIP_ID NUMBER,
	CONSTRAINT FK_APPLY_CHILD FOREIGN KEY(CHILD_ID)
	REFERENCES TBL_CHILD(ID),
	CONSTRAINT FK_APPLY_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
	REFERENCES TBL_FIELD_TRIP(ID)
);

/*부모 테이블*/
INSERT INTO TBL_PARENT(ID, PARENT_NAME, PARENT_AGE, PARENT_ADDRESS, PARENT_PHONE, PARENT_GENDER)
VALUES(SEQ_PARENT.NEXTVAL, '한동석', '40', '경기도 남양주', '01012341234', '남자');
INSERT INTO TBL_PARENT(ID, PARENT_NAME, PARENT_AGE, PARENT_ADDRESS, PARENT_PHONE, PARENT_GENDER)
VALUES(SEQ_PARENT.NEXTVAL, '홍길동', '50', '서울시 강남구', '01055556666', '여자');
INSERT INTO TBL_PARENT(ID, PARENT_NAME, PARENT_AGE, PARENT_ADDRESS, PARENT_PHONE, PARENT_GENDER)
VALUES(SEQ_PARENT.NEXTVAL, '이순신', '55', '서울시 강남구', '01077778888', '여자');

SELECT * FROM TBL_PARENT;
/*아이 테이블*/
INSERT INTO TBL_CHILD(ID, CHILD_NAME, CHILD_AGE, CHILD_GENDER, PARENT_ID) 
VALUES(SEQ_CHILD.NEXTVAL, '김철수', 4, '남자', 1);
INSERT INTO TBL_CHILD(ID, CHILD_NAME, CHILD_AGE, CHILD_GENDER, PARENT_ID) 
VALUES(SEQ_CHILD.NEXTVAL, '김훈이', 5, '남자', 2);
INSERT INTO TBL_CHILD(ID, CHILD_NAME, CHILD_AGE, CHILD_GENDER, PARENT_ID) 
VALUES(SEQ_CHILD.NEXTVAL, '이유리', 7, '여자', 1);
INSERT INTO TBL_CHILD(ID, CHILD_NAME, CHILD_AGE, CHILD_GENDER, PARENT_ID) 
VALUES(SEQ_CHILD.NEXTVAL, '김사자', 4, '남자', 3);
INSERT INTO TBL_CHILD(ID, CHILD_NAME, CHILD_AGE, CHILD_GENDER, PARENT_ID) 
VALUES(SEQ_CHILD.NEXTVAL, '김영희', 4, '여자', 3);

SELECT * FROM TBL_CHILD;

/*체험학습 테이블*/
INSERT INTO TBL_FIELD_TRIP(ID, FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT, FIELD_TRIP_NUMBER)
VALUES(SEQ_FIELD_TRIP.NEXTVAL, '매미 잡기 체험학습', '매미 잡으러 떠나자!', 5);
INSERT INTO TBL_FIELD_TRIP(ID, FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT, FIELD_TRIP_NUMBER)
VALUES(SEQ_FIELD_TRIP.NEXTVAL, '메뚜기 때려 잡기 체험학습', '메뚜기 다 잡자!', 50);
INSERT INTO TBL_FIELD_TRIP(ID, FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT, FIELD_TRIP_NUMBER)
VALUES(SEQ_FIELD_TRIP.NEXTVAL, '물놀이 체험학습', '한강 수영장으로 퐁당!', 20);
INSERT INTO TBL_FIELD_TRIP(ID, FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT, FIELD_TRIP_NUMBER)
VALUES(SEQ_FIELD_TRIP.NEXTVAL, '블루베리 채집 체험학습', '맛있어 블루베리 냠냠!', 25);
INSERT INTO TBL_FIELD_TRIP(ID, FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT, FIELD_TRIP_NUMBER)
VALUES(SEQ_FIELD_TRIP.NEXTVAL, '코딩 체험학습', '나도 빌게이츠!', 20);

SELECT * FROM TBL_FIELD_TRIP;

/*신청하기*/
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 1, 1);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 2, 1);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 3, 2);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 4, 3);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 4, 5);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 5, 5);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 5, 4);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 5, 4);
INSERT INTO TBL_APPLY(ID, CHILD_ID, FIELD_TRIP_ID)
VALUES(SEQ_APPLY.NEXTVAL, 5, 3);

SELECT * FROM TBL_APPLY;

/*매미 체험학습에 신청한 아이의 전체 정보*/
/*1. 서브쿼리만 사용*/
SELECT *
FROM TBL_CHILD C
WHERE C.ID IN
(
	SELECT CHILD_ID 
	FROM TBL_APPLY
	WHERE FIELD_TRIP_ID IN
	(
		SELECT ID
		FROM TBL_FIELD_TRIP
		WHERE FIELD_TRIP_TITLE LIKE '%매미%'
	)
);

/*2. JOIN만 사용*/
SELECT C.* FROM TBL_FIELD_TRIP FT
INNER JOIN TBL_APPLY A
ON FT.FIELD_TRIP_TITLE LIKE '%매미%' AND FT.ID = A.FIELD_TRIP_ID
INNER JOIN TBL_CHILD C 
ON A.CHILD_ID = C.ID;

/*체험학습을 2개 이상 신청한 아이의 정보와 부모의 정보 모두 조회*/

SELECT * FROM TBL_PARENT P
INNER JOIN
(
	SELECT * FROM TBL_CHILD
	WHERE ID IN
	(
		SELECT CHILD_ID FROM TBL_APPLY 
		GROUP BY CHILD_ID
		HAVING COUNT(FIELD_TRIP_ID) >= 2
	)
) C
ON P.ID = C.PARENT_ID;

/*참가자(지원자) 수가 가장 적은 체험학습의 제목과 내용 조회*/
SELECT * FROM TBL_FIELD_TRIP;
SELECT * FROM TBL_APPLY;

SELECT FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT FROM TBL_FIELD_TRIP
WHERE ID =
(
	SELECT FIELD_TRIP_ID FROM TBL_APPLY
	GROUP BY FIELD_TRIP_ID
	HAVING COUNT(CHILD_ID) =
	(
		SELECT MIN(CHILD_COUNT) FROM
		(
			SELECT FIELD_TRIP_ID, COUNT(CHILD_ID) CHILD_COUNT FROM TBL_APPLY
			GROUP BY FIELD_TRIP_ID
		)
	)
);

/*평균 참가자(지원자) 수보다 적은 체험학습의 제목과 내용 조회*/
SELECT FIELD_TRIP_TITLE, FIELD_TRIP_CONTENT FROM TBL_FIELD_TRIP
WHERE ID IN
(
	SELECT FIELD_TRIP_ID FROM TBL_APPLY
	GROUP BY FIELD_TRIP_ID
	HAVING COUNT(CHILD_ID) <
	(
		SELECT AVG(CHILD_COUNT) FROM 
		(
			SELECT COUNT(CHILD_ID) CHILD_COUNT FROM TBL_APPLY
			GROUP BY FIELD_TRIP_ID
		)
	)
);