CREATE TABLE TBL_MEMBER(
	MEMBER_NAME VARCHAR2(255),
	MEMBER_AGE NUMBER
);

DROP TABLE TBL_MEMBER;

-- 자동차 테이블 생성
-- 자동차 번호
-- 자동차 브랜드
-- 출시날짜
-- 색상
-- 가격
CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_BRAND VARCHAR2(255),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(255),
	CAR_PRICE NUMBER
);

DROP TABLE TBL_CAR;

ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;
ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(ID);

-- 동물 테이블 생성
--   고유번호
--   종류
--   나이
--   먹이
CREATE TABLE TBL_ANIMAL(
	ID NUMBER,
	ANIMAL_TYPE VARCHAR2(255),
	ANIMAL_AGE NUMBER,
	ANIMAL_FEED NUMBER
);

-- 제약조건 추가(PK)
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY(ID);

-- 제약조건 삭제(PK)
ALTER TABLE TBL_ANIMAL DROP CONSTRAINT PK_ANIMAL;

-- 컬럼 추가(성별)
ALTER TABLE TBL_ANIMAL ADD(GENDER CHAR(1));
-- 컬럼 이름 수정
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_FEED TO ANIMAL_FEED_NAME;

-- 컬럼 삭제
ALTER TABLE TBL_ANIMAL DROP COLUMN GENDER;

-- 컬럼 수정(자료형)
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_FEED_NAME VARCHAR2(255));

-- 테이블 삭제
DROP TABLE TBL_ANIMAL;

CREATE TABLE TBL_STUDENT(
	ID NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
	STUDENT_ID VARCHAR2(255) UNIQUE,
	STUDENT_NAME VARCHAR2(255) NOT NULL,
	STUDENT_MAJOR VARCHAR2(255) NOT NULL,
	STUDENT_GENDER CHAR(1) DEFAULT 'N' CONSTRAINT BAN_GENDER CHECK(STUDENT_GENDER IN('M', 'F')),
	STUDENT_BIRTH DATE CONSTRAINT BAN_DATE CHECK(STUDENT_BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD'))
);





















